name: Build ISO

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            arch: AMD64
          - runner: ubuntu-24.04-arm
            arch: ARM64
    runs-on: ${{ matrix.runner }}
    container:
      image: ghcr.io/vanilla-os/pico:main
      volumes:
        - /proc:/proc
        - /:/run/host
      options: --privileged -it

    steps:
    - uses: actions/checkout@v4

    - name: Install needed packages
      run: apt update && apt install debootstrap -y

    - name: Build ISO
      run: ./build.sh etc/terraform.conf

    - name: Get current date
      run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"

    - uses: actions/upload-artifact@v4
      with:
        name: VanillaOS 2 Orchid ${{ matrix.arch }} ${{ env.CURRENT_DATE }}
        path: builds/
