name: Upload ISO to the Latest Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download Vanilla OS latest ISO
      run: |
        curl -s https://info.vanillaos.org/downloads.json | jq -r '.[] | .Iso, .Sha256' | while read -r url; do
          wget "$url"
        done

    - name: Upload ISO and TXT files to Release
      if: github.repository == 'vanilla-os/live-iso'
      run: |
        gh release upload "3.0" *.iso *.txt --clobber --repo vanilla-os/live-iso
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
